# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/ubuntu/.local/lib/python3.8/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /home/ubuntu/.local/lib/python3.8/site-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /disk2/Kichang/mllm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /disk2/Kichang/mllm/android

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/home/ubuntu/.local/lib/python3.8/site-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/home/ubuntu/.local/lib/python3.8/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\" \"gmock\" \"gtest\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/home/ubuntu/.local/lib/python3.8/site-packages/cmake/data/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/home/ubuntu/.local/lib/python3.8/site-packages/cmake/data/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/home/ubuntu/.local/lib/python3.8/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/home/ubuntu/.local/lib/python3.8/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/home/ubuntu/.local/lib/python3.8/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/home/ubuntu/.local/lib/python3.8/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /disk2/Kichang/mllm/android/CMakeFiles /disk2/Kichang/mllm/android//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /disk2/Kichang/mllm/android/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mllm_lib

# Build rule for target.
mllm_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mllm_lib
.PHONY : mllm_lib

# fast build rule for target.
mllm_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/build
.PHONY : mllm_lib/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f third_party/googletest/googlemock/CMakeFiles/gmock.dir/build.make third_party/googletest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f third_party/googletest/googlemock/CMakeFiles/gmock_main.dir/build.make third_party/googletest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f third_party/googletest/googletest/CMakeFiles/gtest.dir/build.make third_party/googletest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f third_party/googletest/googletest/CMakeFiles/gtest_main.dir/build.make third_party/googletest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named fmt

# Build rule for target.
fmt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fmt
.PHONY : fmt

# fast build rule for target.
fmt/fast:
	$(MAKE) $(MAKESILENT) -f third_party/fmt/CMakeFiles/fmt.dir/build.make third_party/fmt/CMakeFiles/fmt.dir/build
.PHONY : fmt/fast

#=============================================================================
# Target rules for targets named MLLM_CPU

# Build rule for target.
MLLM_CPU: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MLLM_CPU
.PHONY : MLLM_CPU

# fast build rule for target.
MLLM_CPU/fast:
	$(MAKE) $(MAKESILENT) -f src/backends/cpu/CMakeFiles/MLLM_CPU.dir/build.make src/backends/cpu/CMakeFiles/MLLM_CPU.dir/build
.PHONY : MLLM_CPU/fast

#=============================================================================
# Target rules for targets named MLLM_QNN

# Build rule for target.
MLLM_QNN: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MLLM_QNN
.PHONY : MLLM_QNN

# fast build rule for target.
MLLM_QNN/fast:
	$(MAKE) $(MAKESILENT) -f src/backends/qnn/CMakeFiles/MLLM_QNN.dir/build.make src/backends/qnn/CMakeFiles/MLLM_QNN.dir/build
.PHONY : MLLM_QNN/fast

#=============================================================================
# Target rules for targets named mllm_benchmark

# Build rule for target.
mllm_benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mllm_benchmark
.PHONY : mllm_benchmark

# fast build rule for target.
mllm_benchmark/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/mllm_benchmark.dir/build.make examples/CMakeFiles/mllm_benchmark.dir/build
.PHONY : mllm_benchmark/fast

#=============================================================================
# Target rules for targets named demo_llama

# Build rule for target.
demo_llama: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_llama
.PHONY : demo_llama

# fast build rule for target.
demo_llama/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/demo_llama.dir/build.make examples/CMakeFiles/demo_llama.dir/build
.PHONY : demo_llama/fast

#=============================================================================
# Target rules for targets named demo_tinyllama

# Build rule for target.
demo_tinyllama: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_tinyllama
.PHONY : demo_tinyllama

# fast build rule for target.
demo_tinyllama/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/demo_tinyllama.dir/build.make examples/CMakeFiles/demo_tinyllama.dir/build
.PHONY : demo_tinyllama/fast

#=============================================================================
# Target rules for targets named demo_stablelm

# Build rule for target.
demo_stablelm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_stablelm
.PHONY : demo_stablelm

# fast build rule for target.
demo_stablelm/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/demo_stablelm.dir/build.make examples/CMakeFiles/demo_stablelm.dir/build
.PHONY : demo_stablelm/fast

#=============================================================================
# Target rules for targets named demo_sparse_llama

# Build rule for target.
demo_sparse_llama: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_sparse_llama
.PHONY : demo_sparse_llama

# fast build rule for target.
demo_sparse_llama/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/demo_sparse_llama.dir/build.make examples/CMakeFiles/demo_sparse_llama.dir/build
.PHONY : demo_sparse_llama/fast

#=============================================================================
# Target rules for targets named demo_elastic_llama

# Build rule for target.
demo_elastic_llama: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_elastic_llama
.PHONY : demo_elastic_llama

# fast build rule for target.
demo_elastic_llama/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/demo_elastic_llama.dir/build.make examples/CMakeFiles/demo_elastic_llama.dir/build
.PHONY : demo_elastic_llama/fast

#=============================================================================
# Target rules for targets named demo_gemma

# Build rule for target.
demo_gemma: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_gemma
.PHONY : demo_gemma

# fast build rule for target.
demo_gemma/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/demo_gemma.dir/build.make examples/CMakeFiles/demo_gemma.dir/build
.PHONY : demo_gemma/fast

#=============================================================================
# Target rules for targets named demo_gemma2

# Build rule for target.
demo_gemma2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_gemma2
.PHONY : demo_gemma2

# fast build rule for target.
demo_gemma2/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/demo_gemma2.dir/build.make examples/CMakeFiles/demo_gemma2.dir/build
.PHONY : demo_gemma2/fast

#=============================================================================
# Target rules for targets named demo_qwen

# Build rule for target.
demo_qwen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_qwen
.PHONY : demo_qwen

# fast build rule for target.
demo_qwen/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/demo_qwen.dir/build.make examples/CMakeFiles/demo_qwen.dir/build
.PHONY : demo_qwen/fast

#=============================================================================
# Target rules for targets named demo_ds_qwen2

# Build rule for target.
demo_ds_qwen2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_ds_qwen2
.PHONY : demo_ds_qwen2

# fast build rule for target.
demo_ds_qwen2/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/demo_ds_qwen2.dir/build.make examples/CMakeFiles/demo_ds_qwen2.dir/build
.PHONY : demo_ds_qwen2/fast

#=============================================================================
# Target rules for targets named demo_mistral

# Build rule for target.
demo_mistral: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_mistral
.PHONY : demo_mistral

# fast build rule for target.
demo_mistral/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/demo_mistral.dir/build.make examples/CMakeFiles/demo_mistral.dir/build
.PHONY : demo_mistral/fast

#=============================================================================
# Target rules for targets named demo_yi

# Build rule for target.
demo_yi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_yi
.PHONY : demo_yi

# fast build rule for target.
demo_yi/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/demo_yi.dir/build.make examples/CMakeFiles/demo_yi.dir/build
.PHONY : demo_yi/fast

#=============================================================================
# Target rules for targets named demo_opt

# Build rule for target.
demo_opt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_opt
.PHONY : demo_opt

# fast build rule for target.
demo_opt/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/demo_opt.dir/build.make examples/CMakeFiles/demo_opt.dir/build
.PHONY : demo_opt/fast

#=============================================================================
# Target rules for targets named demo_phi3

# Build rule for target.
demo_phi3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_phi3
.PHONY : demo_phi3

# fast build rule for target.
demo_phi3/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/demo_phi3.dir/build.make examples/CMakeFiles/demo_phi3.dir/build
.PHONY : demo_phi3/fast

#=============================================================================
# Target rules for targets named demo_minicpm

# Build rule for target.
demo_minicpm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_minicpm
.PHONY : demo_minicpm

# fast build rule for target.
demo_minicpm/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/demo_minicpm.dir/build.make examples/CMakeFiles/demo_minicpm.dir/build
.PHONY : demo_minicpm/fast

#=============================================================================
# Target rules for targets named demo_minicpm3

# Build rule for target.
demo_minicpm3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_minicpm3
.PHONY : demo_minicpm3

# fast build rule for target.
demo_minicpm3/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/demo_minicpm3.dir/build.make examples/CMakeFiles/demo_minicpm3.dir/build
.PHONY : demo_minicpm3/fast

#=============================================================================
# Target rules for targets named demo_minicpm_moe

# Build rule for target.
demo_minicpm_moe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_minicpm_moe
.PHONY : demo_minicpm_moe

# fast build rule for target.
demo_minicpm_moe/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/demo_minicpm_moe.dir/build.make examples/CMakeFiles/demo_minicpm_moe.dir/build
.PHONY : demo_minicpm_moe/fast

#=============================================================================
# Target rules for targets named demo_smollm

# Build rule for target.
demo_smollm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_smollm
.PHONY : demo_smollm

# fast build rule for target.
demo_smollm/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/demo_smollm.dir/build.make examples/CMakeFiles/demo_smollm.dir/build
.PHONY : demo_smollm/fast

#=============================================================================
# Target rules for targets named demo_openelm

# Build rule for target.
demo_openelm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_openelm
.PHONY : demo_openelm

# fast build rule for target.
demo_openelm/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/demo_openelm.dir/build.make examples/CMakeFiles/demo_openelm.dir/build
.PHONY : demo_openelm/fast

#=============================================================================
# Target rules for targets named demo_dclm

# Build rule for target.
demo_dclm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_dclm
.PHONY : demo_dclm

# fast build rule for target.
demo_dclm/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/demo_dclm.dir/build.make examples/CMakeFiles/demo_dclm.dir/build
.PHONY : demo_dclm/fast

#=============================================================================
# Target rules for targets named demo_bert

# Build rule for target.
demo_bert: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_bert
.PHONY : demo_bert

# fast build rule for target.
demo_bert/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/demo_bert.dir/build.make examples/CMakeFiles/demo_bert.dir/build
.PHONY : demo_bert/fast

#=============================================================================
# Target rules for targets named demo_phonelm

# Build rule for target.
demo_phonelm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_phonelm
.PHONY : demo_phonelm

# fast build rule for target.
demo_phonelm/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/demo_phonelm.dir/build.make examples/CMakeFiles/demo_phonelm.dir/build
.PHONY : demo_phonelm/fast

#=============================================================================
# Target rules for targets named demo_llama3

# Build rule for target.
demo_llama3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_llama3
.PHONY : demo_llama3

# fast build rule for target.
demo_llama3/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/demo_llama3.dir/build.make examples/CMakeFiles/demo_llama3.dir/build
.PHONY : demo_llama3/fast

#=============================================================================
# Target rules for targets named demo_minicpm_moe_mbm

# Build rule for target.
demo_minicpm_moe_mbm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_minicpm_moe_mbm
.PHONY : demo_minicpm_moe_mbm

# fast build rule for target.
demo_minicpm_moe_mbm/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/demo_minicpm_moe_mbm.dir/build.make examples/CMakeFiles/demo_minicpm_moe_mbm.dir/build
.PHONY : demo_minicpm_moe_mbm/fast

#=============================================================================
# Target rules for targets named demo_llava

# Build rule for target.
demo_llava: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_llava
.PHONY : demo_llava

# fast build rule for target.
demo_llava/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/demo_llava.dir/build.make examples/CMakeFiles/demo_llava.dir/build
.PHONY : demo_llava/fast

#=============================================================================
# Target rules for targets named demo_fuyu

# Build rule for target.
demo_fuyu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_fuyu
.PHONY : demo_fuyu

# fast build rule for target.
demo_fuyu/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/demo_fuyu.dir/build.make examples/CMakeFiles/demo_fuyu.dir/build
.PHONY : demo_fuyu/fast

#=============================================================================
# Target rules for targets named demo_vit

# Build rule for target.
demo_vit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_vit
.PHONY : demo_vit

# fast build rule for target.
demo_vit/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/demo_vit.dir/build.make examples/CMakeFiles/demo_vit.dir/build
.PHONY : demo_vit/fast

#=============================================================================
# Target rules for targets named demo_clip

# Build rule for target.
demo_clip: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_clip
.PHONY : demo_clip

# fast build rule for target.
demo_clip/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/demo_clip.dir/build.make examples/CMakeFiles/demo_clip.dir/build
.PHONY : demo_clip/fast

#=============================================================================
# Target rules for targets named demo_imagebind

# Build rule for target.
demo_imagebind: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_imagebind
.PHONY : demo_imagebind

# fast build rule for target.
demo_imagebind/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/demo_imagebind.dir/build.make examples/CMakeFiles/demo_imagebind.dir/build
.PHONY : demo_imagebind/fast

#=============================================================================
# Target rules for targets named demo_imagebind_1mod

# Build rule for target.
demo_imagebind_1mod: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_imagebind_1mod
.PHONY : demo_imagebind_1mod

# fast build rule for target.
demo_imagebind_1mod/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/demo_imagebind_1mod.dir/build.make examples/CMakeFiles/demo_imagebind_1mod.dir/build
.PHONY : demo_imagebind_1mod/fast

#=============================================================================
# Target rules for targets named demo_phi3v

# Build rule for target.
demo_phi3v: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_phi3v
.PHONY : demo_phi3v

# fast build rule for target.
demo_phi3v/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/demo_phi3v.dir/build.make examples/CMakeFiles/demo_phi3v.dir/build
.PHONY : demo_phi3v/fast

#=============================================================================
# Target rules for targets named demo_qwen2_vl

# Build rule for target.
demo_qwen2_vl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_qwen2_vl
.PHONY : demo_qwen2_vl

# fast build rule for target.
demo_qwen2_vl/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/demo_qwen2_vl.dir/build.make examples/CMakeFiles/demo_qwen2_vl.dir/build
.PHONY : demo_qwen2_vl/fast

#=============================================================================
# Target rules for targets named demo_qwen_npu

# Build rule for target.
demo_qwen_npu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_qwen_npu
.PHONY : demo_qwen_npu

# fast build rule for target.
demo_qwen_npu/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/demo_qwen_npu.dir/build.make examples/CMakeFiles/demo_qwen_npu.dir/build
.PHONY : demo_qwen_npu/fast

#=============================================================================
# Target rules for targets named main_qwen_npu

# Build rule for target.
main_qwen_npu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main_qwen_npu
.PHONY : main_qwen_npu

# fast build rule for target.
main_qwen_npu/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/main_qwen_npu.dir/build.make examples/CMakeFiles/main_qwen_npu.dir/build
.PHONY : main_qwen_npu/fast

#=============================================================================
# Target rules for targets named demo_phonelm_npu

# Build rule for target.
demo_phonelm_npu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_phonelm_npu
.PHONY : demo_phonelm_npu

# fast build rule for target.
demo_phonelm_npu/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/demo_phonelm_npu.dir/build.make examples/CMakeFiles/demo_phonelm_npu.dir/build
.PHONY : demo_phonelm_npu/fast

#=============================================================================
# Target rules for targets named main_phonelm_npu

# Build rule for target.
main_phonelm_npu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main_phonelm_npu
.PHONY : main_phonelm_npu

# fast build rule for target.
main_phonelm_npu/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/main_phonelm_npu.dir/build.make examples/CMakeFiles/main_phonelm_npu.dir/build
.PHONY : main_phonelm_npu/fast

#=============================================================================
# Target rules for targets named demo_qwen2.5_npu

# Build rule for target.
demo_qwen2.5_npu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_qwen2.5_npu
.PHONY : demo_qwen2.5_npu

# fast build rule for target.
demo_qwen2.5_npu/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/demo_qwen2.5_npu.dir/build.make examples/CMakeFiles/demo_qwen2.5_npu.dir/build
.PHONY : demo_qwen2.5_npu/fast

#=============================================================================
# Target rules for targets named demo_qwen_pipeline

# Build rule for target.
demo_qwen_pipeline: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_qwen_pipeline
.PHONY : demo_qwen_pipeline

# fast build rule for target.
demo_qwen_pipeline/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/demo_qwen_pipeline.dir/build.make examples/CMakeFiles/demo_qwen_pipeline.dir/build
.PHONY : demo_qwen_pipeline/fast

src/Backend.o: src/Backend.cpp.o
.PHONY : src/Backend.o

# target to build an object file
src/Backend.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/Backend.cpp.o
.PHONY : src/Backend.cpp.o

src/Backend.i: src/Backend.cpp.i
.PHONY : src/Backend.i

# target to preprocess a source file
src/Backend.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/Backend.cpp.i
.PHONY : src/Backend.cpp.i

src/Backend.s: src/Backend.cpp.s
.PHONY : src/Backend.s

# target to generate assembly for a file
src/Backend.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/Backend.cpp.s
.PHONY : src/Backend.cpp.s

src/Executor.o: src/Executor.cpp.o
.PHONY : src/Executor.o

# target to build an object file
src/Executor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/Executor.cpp.o
.PHONY : src/Executor.cpp.o

src/Executor.i: src/Executor.cpp.i
.PHONY : src/Executor.i

# target to preprocess a source file
src/Executor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/Executor.cpp.i
.PHONY : src/Executor.cpp.i

src/Executor.s: src/Executor.cpp.s
.PHONY : src/Executor.s

# target to generate assembly for a file
src/Executor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/Executor.cpp.s
.PHONY : src/Executor.cpp.s

src/Generate.o: src/Generate.cpp.o
.PHONY : src/Generate.o

# target to build an object file
src/Generate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/Generate.cpp.o
.PHONY : src/Generate.cpp.o

src/Generate.i: src/Generate.cpp.i
.PHONY : src/Generate.i

# target to preprocess a source file
src/Generate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/Generate.cpp.i
.PHONY : src/Generate.cpp.i

src/Generate.s: src/Generate.cpp.s
.PHONY : src/Generate.s

# target to generate assembly for a file
src/Generate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/Generate.cpp.s
.PHONY : src/Generate.cpp.s

src/Graph.o: src/Graph.cpp.o
.PHONY : src/Graph.o

# target to build an object file
src/Graph.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/Graph.cpp.o
.PHONY : src/Graph.cpp.o

src/Graph.i: src/Graph.cpp.i
.PHONY : src/Graph.i

# target to preprocess a source file
src/Graph.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/Graph.cpp.i
.PHONY : src/Graph.cpp.i

src/Graph.s: src/Graph.cpp.s
.PHONY : src/Graph.s

# target to generate assembly for a file
src/Graph.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/Graph.cpp.s
.PHONY : src/Graph.cpp.s

src/Layer.o: src/Layer.cpp.o
.PHONY : src/Layer.o

# target to build an object file
src/Layer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/Layer.cpp.o
.PHONY : src/Layer.cpp.o

src/Layer.i: src/Layer.cpp.i
.PHONY : src/Layer.i

# target to preprocess a source file
src/Layer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/Layer.cpp.i
.PHONY : src/Layer.cpp.i

src/Layer.s: src/Layer.cpp.s
.PHONY : src/Layer.s

# target to generate assembly for a file
src/Layer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/Layer.cpp.s
.PHONY : src/Layer.cpp.s

src/Log.o: src/Log.cpp.o
.PHONY : src/Log.o

# target to build an object file
src/Log.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/Log.cpp.o
.PHONY : src/Log.cpp.o

src/Log.i: src/Log.cpp.i
.PHONY : src/Log.i

# target to preprocess a source file
src/Log.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/Log.cpp.i
.PHONY : src/Log.cpp.i

src/Log.s: src/Log.cpp.s
.PHONY : src/Log.s

# target to generate assembly for a file
src/Log.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/Log.cpp.s
.PHONY : src/Log.cpp.s

src/MemoryManager.o: src/MemoryManager.cpp.o
.PHONY : src/MemoryManager.o

# target to build an object file
src/MemoryManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/MemoryManager.cpp.o
.PHONY : src/MemoryManager.cpp.o

src/MemoryManager.i: src/MemoryManager.cpp.i
.PHONY : src/MemoryManager.i

# target to preprocess a source file
src/MemoryManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/MemoryManager.cpp.i
.PHONY : src/MemoryManager.cpp.i

src/MemoryManager.s: src/MemoryManager.cpp.s
.PHONY : src/MemoryManager.s

# target to generate assembly for a file
src/MemoryManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/MemoryManager.cpp.s
.PHONY : src/MemoryManager.cpp.s

src/Module.o: src/Module.cpp.o
.PHONY : src/Module.o

# target to build an object file
src/Module.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/Module.cpp.o
.PHONY : src/Module.cpp.o

src/Module.i: src/Module.cpp.i
.PHONY : src/Module.i

# target to preprocess a source file
src/Module.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/Module.cpp.i
.PHONY : src/Module.cpp.i

src/Module.s: src/Module.cpp.s
.PHONY : src/Module.s

# target to generate assembly for a file
src/Module.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/Module.cpp.s
.PHONY : src/Module.cpp.s

src/Net.o: src/Net.cpp.o
.PHONY : src/Net.o

# target to build an object file
src/Net.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/Net.cpp.o
.PHONY : src/Net.cpp.o

src/Net.i: src/Net.cpp.i
.PHONY : src/Net.i

# target to preprocess a source file
src/Net.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/Net.cpp.i
.PHONY : src/Net.cpp.i

src/Net.s: src/Net.cpp.s
.PHONY : src/Net.s

# target to generate assembly for a file
src/Net.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/Net.cpp.s
.PHONY : src/Net.cpp.s

src/Op.o: src/Op.cpp.o
.PHONY : src/Op.o

# target to build an object file
src/Op.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/Op.cpp.o
.PHONY : src/Op.cpp.o

src/Op.i: src/Op.cpp.i
.PHONY : src/Op.i

# target to preprocess a source file
src/Op.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/Op.cpp.i
.PHONY : src/Op.cpp.i

src/Op.s: src/Op.cpp.s
.PHONY : src/Op.s

# target to generate assembly for a file
src/Op.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/Op.cpp.s
.PHONY : src/Op.cpp.s

src/Parallel.o: src/Parallel.cpp.o
.PHONY : src/Parallel.o

# target to build an object file
src/Parallel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/Parallel.cpp.o
.PHONY : src/Parallel.cpp.o

src/Parallel.i: src/Parallel.cpp.i
.PHONY : src/Parallel.i

# target to preprocess a source file
src/Parallel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/Parallel.cpp.i
.PHONY : src/Parallel.cpp.i

src/Parallel.s: src/Parallel.cpp.s
.PHONY : src/Parallel.s

# target to generate assembly for a file
src/Parallel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/Parallel.cpp.s
.PHONY : src/Parallel.cpp.s

src/ParamLoader.o: src/ParamLoader.cpp.o
.PHONY : src/ParamLoader.o

# target to build an object file
src/ParamLoader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/ParamLoader.cpp.o
.PHONY : src/ParamLoader.cpp.o

src/ParamLoader.i: src/ParamLoader.cpp.i
.PHONY : src/ParamLoader.i

# target to preprocess a source file
src/ParamLoader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/ParamLoader.cpp.i
.PHONY : src/ParamLoader.cpp.i

src/ParamLoader.s: src/ParamLoader.cpp.s
.PHONY : src/ParamLoader.s

# target to generate assembly for a file
src/ParamLoader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/ParamLoader.cpp.s
.PHONY : src/ParamLoader.cpp.s

src/Tensor.o: src/Tensor.cpp.o
.PHONY : src/Tensor.o

# target to build an object file
src/Tensor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/Tensor.cpp.o
.PHONY : src/Tensor.cpp.o

src/Tensor.i: src/Tensor.cpp.i
.PHONY : src/Tensor.i

# target to preprocess a source file
src/Tensor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/Tensor.cpp.i
.PHONY : src/Tensor.cpp.i

src/Tensor.s: src/Tensor.cpp.s
.PHONY : src/Tensor.s

# target to generate assembly for a file
src/Tensor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/Tensor.cpp.s
.PHONY : src/Tensor.cpp.s

src/Trace.o: src/Trace.cpp.o
.PHONY : src/Trace.o

# target to build an object file
src/Trace.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/Trace.cpp.o
.PHONY : src/Trace.cpp.o

src/Trace.i: src/Trace.cpp.i
.PHONY : src/Trace.i

# target to preprocess a source file
src/Trace.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/Trace.cpp.i
.PHONY : src/Trace.cpp.i

src/Trace.s: src/Trace.cpp.s
.PHONY : src/Trace.s

# target to generate assembly for a file
src/Trace.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/Trace.cpp.s
.PHONY : src/Trace.cpp.s

src/express/Express.o: src/express/Express.cpp.o
.PHONY : src/express/Express.o

# target to build an object file
src/express/Express.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/express/Express.cpp.o
.PHONY : src/express/Express.cpp.o

src/express/Express.i: src/express/Express.cpp.i
.PHONY : src/express/Express.i

# target to preprocess a source file
src/express/Express.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/express/Express.cpp.i
.PHONY : src/express/Express.cpp.i

src/express/Express.s: src/express/Express.cpp.s
.PHONY : src/express/Express.s

# target to generate assembly for a file
src/express/Express.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/express/Express.cpp.s
.PHONY : src/express/Express.cpp.s

src/express/ExpressBase.o: src/express/ExpressBase.cpp.o
.PHONY : src/express/ExpressBase.o

# target to build an object file
src/express/ExpressBase.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/express/ExpressBase.cpp.o
.PHONY : src/express/ExpressBase.cpp.o

src/express/ExpressBase.i: src/express/ExpressBase.cpp.i
.PHONY : src/express/ExpressBase.i

# target to preprocess a source file
src/express/ExpressBase.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/express/ExpressBase.cpp.i
.PHONY : src/express/ExpressBase.cpp.i

src/express/ExpressBase.s: src/express/ExpressBase.cpp.s
.PHONY : src/express/ExpressBase.s

# target to generate assembly for a file
src/express/ExpressBase.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/express/ExpressBase.cpp.s
.PHONY : src/express/ExpressBase.cpp.s

src/memory/MemInspect.o: src/memory/MemInspect.cpp.o
.PHONY : src/memory/MemInspect.o

# target to build an object file
src/memory/MemInspect.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/memory/MemInspect.cpp.o
.PHONY : src/memory/MemInspect.cpp.o

src/memory/MemInspect.i: src/memory/MemInspect.cpp.i
.PHONY : src/memory/MemInspect.i

# target to preprocess a source file
src/memory/MemInspect.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/memory/MemInspect.cpp.i
.PHONY : src/memory/MemInspect.cpp.i

src/memory/MemInspect.s: src/memory/MemInspect.cpp.s
.PHONY : src/memory/MemInspect.s

# target to generate assembly for a file
src/memory/MemInspect.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/memory/MemInspect.cpp.s
.PHONY : src/memory/MemInspect.cpp.s

src/memory/MemoryPoolManager.o: src/memory/MemoryPoolManager.cpp.o
.PHONY : src/memory/MemoryPoolManager.o

# target to build an object file
src/memory/MemoryPoolManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/memory/MemoryPoolManager.cpp.o
.PHONY : src/memory/MemoryPoolManager.cpp.o

src/memory/MemoryPoolManager.i: src/memory/MemoryPoolManager.cpp.i
.PHONY : src/memory/MemoryPoolManager.i

# target to preprocess a source file
src/memory/MemoryPoolManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/memory/MemoryPoolManager.cpp.i
.PHONY : src/memory/MemoryPoolManager.cpp.i

src/memory/MemoryPoolManager.s: src/memory/MemoryPoolManager.cpp.s
.PHONY : src/memory/MemoryPoolManager.s

# target to generate assembly for a file
src/memory/MemoryPoolManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/memory/MemoryPoolManager.cpp.s
.PHONY : src/memory/MemoryPoolManager.cpp.s

src/memory/SystemMemoryManager.o: src/memory/SystemMemoryManager.cpp.o
.PHONY : src/memory/SystemMemoryManager.o

# target to build an object file
src/memory/SystemMemoryManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/memory/SystemMemoryManager.cpp.o
.PHONY : src/memory/SystemMemoryManager.cpp.o

src/memory/SystemMemoryManager.i: src/memory/SystemMemoryManager.cpp.i
.PHONY : src/memory/SystemMemoryManager.i

# target to preprocess a source file
src/memory/SystemMemoryManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/memory/SystemMemoryManager.cpp.i
.PHONY : src/memory/SystemMemoryManager.cpp.i

src/memory/SystemMemoryManager.s: src/memory/SystemMemoryManager.cpp.s
.PHONY : src/memory/SystemMemoryManager.s

# target to generate assembly for a file
src/memory/SystemMemoryManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/memory/SystemMemoryManager.cpp.s
.PHONY : src/memory/SystemMemoryManager.cpp.s

src/processor/AudioProcess.o: src/processor/AudioProcess.cpp.o
.PHONY : src/processor/AudioProcess.o

# target to build an object file
src/processor/AudioProcess.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/processor/AudioProcess.cpp.o
.PHONY : src/processor/AudioProcess.cpp.o

src/processor/AudioProcess.i: src/processor/AudioProcess.cpp.i
.PHONY : src/processor/AudioProcess.i

# target to preprocess a source file
src/processor/AudioProcess.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/processor/AudioProcess.cpp.i
.PHONY : src/processor/AudioProcess.cpp.i

src/processor/AudioProcess.s: src/processor/AudioProcess.cpp.s
.PHONY : src/processor/AudioProcess.s

# target to generate assembly for a file
src/processor/AudioProcess.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/processor/AudioProcess.cpp.s
.PHONY : src/processor/AudioProcess.cpp.s

src/processor/ClipPreProcess.o: src/processor/ClipPreProcess.cpp.o
.PHONY : src/processor/ClipPreProcess.o

# target to build an object file
src/processor/ClipPreProcess.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/processor/ClipPreProcess.cpp.o
.PHONY : src/processor/ClipPreProcess.cpp.o

src/processor/ClipPreProcess.i: src/processor/ClipPreProcess.cpp.i
.PHONY : src/processor/ClipPreProcess.i

# target to preprocess a source file
src/processor/ClipPreProcess.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/processor/ClipPreProcess.cpp.i
.PHONY : src/processor/ClipPreProcess.cpp.i

src/processor/ClipPreProcess.s: src/processor/ClipPreProcess.cpp.s
.PHONY : src/processor/ClipPreProcess.s

# target to generate assembly for a file
src/processor/ClipPreProcess.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/processor/ClipPreProcess.cpp.s
.PHONY : src/processor/ClipPreProcess.cpp.s

src/processor/FuyuPreProcess.o: src/processor/FuyuPreProcess.cpp.o
.PHONY : src/processor/FuyuPreProcess.o

# target to build an object file
src/processor/FuyuPreProcess.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/processor/FuyuPreProcess.cpp.o
.PHONY : src/processor/FuyuPreProcess.cpp.o

src/processor/FuyuPreProcess.i: src/processor/FuyuPreProcess.cpp.i
.PHONY : src/processor/FuyuPreProcess.i

# target to preprocess a source file
src/processor/FuyuPreProcess.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/processor/FuyuPreProcess.cpp.i
.PHONY : src/processor/FuyuPreProcess.cpp.i

src/processor/FuyuPreProcess.s: src/processor/FuyuPreProcess.cpp.s
.PHONY : src/processor/FuyuPreProcess.s

# target to generate assembly for a file
src/processor/FuyuPreProcess.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/processor/FuyuPreProcess.cpp.s
.PHONY : src/processor/FuyuPreProcess.cpp.s

src/processor/PostProcess.o: src/processor/PostProcess.cpp.o
.PHONY : src/processor/PostProcess.o

# target to build an object file
src/processor/PostProcess.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/processor/PostProcess.cpp.o
.PHONY : src/processor/PostProcess.cpp.o

src/processor/PostProcess.i: src/processor/PostProcess.cpp.i
.PHONY : src/processor/PostProcess.i

# target to preprocess a source file
src/processor/PostProcess.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/processor/PostProcess.cpp.i
.PHONY : src/processor/PostProcess.cpp.i

src/processor/PostProcess.s: src/processor/PostProcess.cpp.s
.PHONY : src/processor/PostProcess.s

# target to generate assembly for a file
src/processor/PostProcess.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/processor/PostProcess.cpp.s
.PHONY : src/processor/PostProcess.cpp.s

src/processor/PreProcess.o: src/processor/PreProcess.cpp.o
.PHONY : src/processor/PreProcess.o

# target to build an object file
src/processor/PreProcess.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/processor/PreProcess.cpp.o
.PHONY : src/processor/PreProcess.cpp.o

src/processor/PreProcess.i: src/processor/PreProcess.cpp.i
.PHONY : src/processor/PreProcess.i

# target to preprocess a source file
src/processor/PreProcess.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/processor/PreProcess.cpp.i
.PHONY : src/processor/PreProcess.cpp.i

src/processor/PreProcess.s: src/processor/PreProcess.cpp.s
.PHONY : src/processor/PreProcess.s

# target to generate assembly for a file
src/processor/PreProcess.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/processor/PreProcess.cpp.s
.PHONY : src/processor/PreProcess.cpp.s

src/tokenizers/BPE/Bpe.o: src/tokenizers/BPE/Bpe.cpp.o
.PHONY : src/tokenizers/BPE/Bpe.o

# target to build an object file
src/tokenizers/BPE/Bpe.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/tokenizers/BPE/Bpe.cpp.o
.PHONY : src/tokenizers/BPE/Bpe.cpp.o

src/tokenizers/BPE/Bpe.i: src/tokenizers/BPE/Bpe.cpp.i
.PHONY : src/tokenizers/BPE/Bpe.i

# target to preprocess a source file
src/tokenizers/BPE/Bpe.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/tokenizers/BPE/Bpe.cpp.i
.PHONY : src/tokenizers/BPE/Bpe.cpp.i

src/tokenizers/BPE/Bpe.s: src/tokenizers/BPE/Bpe.cpp.s
.PHONY : src/tokenizers/BPE/Bpe.s

# target to generate assembly for a file
src/tokenizers/BPE/Bpe.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/tokenizers/BPE/Bpe.cpp.s
.PHONY : src/tokenizers/BPE/Bpe.cpp.s

src/tokenizers/Tokenizer.o: src/tokenizers/Tokenizer.cpp.o
.PHONY : src/tokenizers/Tokenizer.o

# target to build an object file
src/tokenizers/Tokenizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/tokenizers/Tokenizer.cpp.o
.PHONY : src/tokenizers/Tokenizer.cpp.o

src/tokenizers/Tokenizer.i: src/tokenizers/Tokenizer.cpp.i
.PHONY : src/tokenizers/Tokenizer.i

# target to preprocess a source file
src/tokenizers/Tokenizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/tokenizers/Tokenizer.cpp.i
.PHONY : src/tokenizers/Tokenizer.cpp.i

src/tokenizers/Tokenizer.s: src/tokenizers/Tokenizer.cpp.s
.PHONY : src/tokenizers/Tokenizer.s

# target to generate assembly for a file
src/tokenizers/Tokenizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/tokenizers/Tokenizer.cpp.s
.PHONY : src/tokenizers/Tokenizer.cpp.s

src/tokenizers/Unicode.o: src/tokenizers/Unicode.cpp.o
.PHONY : src/tokenizers/Unicode.o

# target to build an object file
src/tokenizers/Unicode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/tokenizers/Unicode.cpp.o
.PHONY : src/tokenizers/Unicode.cpp.o

src/tokenizers/Unicode.i: src/tokenizers/Unicode.cpp.i
.PHONY : src/tokenizers/Unicode.i

# target to preprocess a source file
src/tokenizers/Unicode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/tokenizers/Unicode.cpp.i
.PHONY : src/tokenizers/Unicode.cpp.i

src/tokenizers/Unicode.s: src/tokenizers/Unicode.cpp.s
.PHONY : src/tokenizers/Unicode.s

# target to generate assembly for a file
src/tokenizers/Unicode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/tokenizers/Unicode.cpp.s
.PHONY : src/tokenizers/Unicode.cpp.s

src/tokenizers/UnicodeData.o: src/tokenizers/UnicodeData.cpp.o
.PHONY : src/tokenizers/UnicodeData.o

# target to build an object file
src/tokenizers/UnicodeData.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/tokenizers/UnicodeData.cpp.o
.PHONY : src/tokenizers/UnicodeData.cpp.o

src/tokenizers/UnicodeData.i: src/tokenizers/UnicodeData.cpp.i
.PHONY : src/tokenizers/UnicodeData.i

# target to preprocess a source file
src/tokenizers/UnicodeData.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/tokenizers/UnicodeData.cpp.i
.PHONY : src/tokenizers/UnicodeData.cpp.i

src/tokenizers/UnicodeData.s: src/tokenizers/UnicodeData.cpp.s
.PHONY : src/tokenizers/UnicodeData.s

# target to generate assembly for a file
src/tokenizers/UnicodeData.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/tokenizers/UnicodeData.cpp.s
.PHONY : src/tokenizers/UnicodeData.cpp.s

src/tokenizers/Unigram/Unigram.o: src/tokenizers/Unigram/Unigram.cpp.o
.PHONY : src/tokenizers/Unigram/Unigram.o

# target to build an object file
src/tokenizers/Unigram/Unigram.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/tokenizers/Unigram/Unigram.cpp.o
.PHONY : src/tokenizers/Unigram/Unigram.cpp.o

src/tokenizers/Unigram/Unigram.i: src/tokenizers/Unigram/Unigram.cpp.i
.PHONY : src/tokenizers/Unigram/Unigram.i

# target to preprocess a source file
src/tokenizers/Unigram/Unigram.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/tokenizers/Unigram/Unigram.cpp.i
.PHONY : src/tokenizers/Unigram/Unigram.cpp.i

src/tokenizers/Unigram/Unigram.s: src/tokenizers/Unigram/Unigram.cpp.s
.PHONY : src/tokenizers/Unigram/Unigram.s

# target to generate assembly for a file
src/tokenizers/Unigram/Unigram.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/tokenizers/Unigram/Unigram.cpp.s
.PHONY : src/tokenizers/Unigram/Unigram.cpp.s

src/tokenizers/WordPiece/WordPiece.o: src/tokenizers/WordPiece/WordPiece.cpp.o
.PHONY : src/tokenizers/WordPiece/WordPiece.o

# target to build an object file
src/tokenizers/WordPiece/WordPiece.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/tokenizers/WordPiece/WordPiece.cpp.o
.PHONY : src/tokenizers/WordPiece/WordPiece.cpp.o

src/tokenizers/WordPiece/WordPiece.i: src/tokenizers/WordPiece/WordPiece.cpp.i
.PHONY : src/tokenizers/WordPiece/WordPiece.i

# target to preprocess a source file
src/tokenizers/WordPiece/WordPiece.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/tokenizers/WordPiece/WordPiece.cpp.i
.PHONY : src/tokenizers/WordPiece/WordPiece.cpp.i

src/tokenizers/WordPiece/WordPiece.s: src/tokenizers/WordPiece/WordPiece.cpp.s
.PHONY : src/tokenizers/WordPiece/WordPiece.s

# target to generate assembly for a file
src/tokenizers/WordPiece/WordPiece.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/src/tokenizers/WordPiece/WordPiece.cpp.s
.PHONY : src/tokenizers/WordPiece/WordPiece.cpp.s

third_party/wenet_audio/feature_pipeline.o: third_party/wenet_audio/feature_pipeline.cc.o
.PHONY : third_party/wenet_audio/feature_pipeline.o

# target to build an object file
third_party/wenet_audio/feature_pipeline.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/third_party/wenet_audio/feature_pipeline.cc.o
.PHONY : third_party/wenet_audio/feature_pipeline.cc.o

third_party/wenet_audio/feature_pipeline.i: third_party/wenet_audio/feature_pipeline.cc.i
.PHONY : third_party/wenet_audio/feature_pipeline.i

# target to preprocess a source file
third_party/wenet_audio/feature_pipeline.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/third_party/wenet_audio/feature_pipeline.cc.i
.PHONY : third_party/wenet_audio/feature_pipeline.cc.i

third_party/wenet_audio/feature_pipeline.s: third_party/wenet_audio/feature_pipeline.cc.s
.PHONY : third_party/wenet_audio/feature_pipeline.s

# target to generate assembly for a file
third_party/wenet_audio/feature_pipeline.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/third_party/wenet_audio/feature_pipeline.cc.s
.PHONY : third_party/wenet_audio/feature_pipeline.cc.s

third_party/wenet_audio/fft.o: third_party/wenet_audio/fft.cc.o
.PHONY : third_party/wenet_audio/fft.o

# target to build an object file
third_party/wenet_audio/fft.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/third_party/wenet_audio/fft.cc.o
.PHONY : third_party/wenet_audio/fft.cc.o

third_party/wenet_audio/fft.i: third_party/wenet_audio/fft.cc.i
.PHONY : third_party/wenet_audio/fft.i

# target to preprocess a source file
third_party/wenet_audio/fft.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/third_party/wenet_audio/fft.cc.i
.PHONY : third_party/wenet_audio/fft.cc.i

third_party/wenet_audio/fft.s: third_party/wenet_audio/fft.cc.s
.PHONY : third_party/wenet_audio/fft.s

# target to generate assembly for a file
third_party/wenet_audio/fft.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/third_party/wenet_audio/fft.cc.s
.PHONY : third_party/wenet_audio/fft.cc.s

tools/jni/LibHelper.o: tools/jni/LibHelper.cpp.o
.PHONY : tools/jni/LibHelper.o

# target to build an object file
tools/jni/LibHelper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/tools/jni/LibHelper.cpp.o
.PHONY : tools/jni/LibHelper.cpp.o

tools/jni/LibHelper.i: tools/jni/LibHelper.cpp.i
.PHONY : tools/jni/LibHelper.i

# target to preprocess a source file
tools/jni/LibHelper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/tools/jni/LibHelper.cpp.i
.PHONY : tools/jni/LibHelper.cpp.i

tools/jni/LibHelper.s: tools/jni/LibHelper.cpp.s
.PHONY : tools/jni/LibHelper.s

# target to generate assembly for a file
tools/jni/LibHelper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mllm_lib.dir/build.make CMakeFiles/mllm_lib.dir/tools/jni/LibHelper.cpp.s
.PHONY : tools/jni/LibHelper.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... MLLM_CPU"
	@echo "... MLLM_QNN"
	@echo "... demo_bert"
	@echo "... demo_clip"
	@echo "... demo_dclm"
	@echo "... demo_ds_qwen2"
	@echo "... demo_elastic_llama"
	@echo "... demo_fuyu"
	@echo "... demo_gemma"
	@echo "... demo_gemma2"
	@echo "... demo_imagebind"
	@echo "... demo_imagebind_1mod"
	@echo "... demo_llama"
	@echo "... demo_llama3"
	@echo "... demo_llava"
	@echo "... demo_minicpm"
	@echo "... demo_minicpm3"
	@echo "... demo_minicpm_moe"
	@echo "... demo_minicpm_moe_mbm"
	@echo "... demo_mistral"
	@echo "... demo_openelm"
	@echo "... demo_opt"
	@echo "... demo_phi3"
	@echo "... demo_phi3v"
	@echo "... demo_phonelm"
	@echo "... demo_phonelm_npu"
	@echo "... demo_qwen"
	@echo "... demo_qwen2.5_npu"
	@echo "... demo_qwen2_vl"
	@echo "... demo_qwen_npu"
	@echo "... demo_qwen_pipeline"
	@echo "... demo_smollm"
	@echo "... demo_sparse_llama"
	@echo "... demo_stablelm"
	@echo "... demo_tinyllama"
	@echo "... demo_vit"
	@echo "... demo_yi"
	@echo "... fmt"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... main_phonelm_npu"
	@echo "... main_qwen_npu"
	@echo "... mllm_benchmark"
	@echo "... mllm_lib"
	@echo "... src/Backend.o"
	@echo "... src/Backend.i"
	@echo "... src/Backend.s"
	@echo "... src/Executor.o"
	@echo "... src/Executor.i"
	@echo "... src/Executor.s"
	@echo "... src/Generate.o"
	@echo "... src/Generate.i"
	@echo "... src/Generate.s"
	@echo "... src/Graph.o"
	@echo "... src/Graph.i"
	@echo "... src/Graph.s"
	@echo "... src/Layer.o"
	@echo "... src/Layer.i"
	@echo "... src/Layer.s"
	@echo "... src/Log.o"
	@echo "... src/Log.i"
	@echo "... src/Log.s"
	@echo "... src/MemoryManager.o"
	@echo "... src/MemoryManager.i"
	@echo "... src/MemoryManager.s"
	@echo "... src/Module.o"
	@echo "... src/Module.i"
	@echo "... src/Module.s"
	@echo "... src/Net.o"
	@echo "... src/Net.i"
	@echo "... src/Net.s"
	@echo "... src/Op.o"
	@echo "... src/Op.i"
	@echo "... src/Op.s"
	@echo "... src/Parallel.o"
	@echo "... src/Parallel.i"
	@echo "... src/Parallel.s"
	@echo "... src/ParamLoader.o"
	@echo "... src/ParamLoader.i"
	@echo "... src/ParamLoader.s"
	@echo "... src/Tensor.o"
	@echo "... src/Tensor.i"
	@echo "... src/Tensor.s"
	@echo "... src/Trace.o"
	@echo "... src/Trace.i"
	@echo "... src/Trace.s"
	@echo "... src/express/Express.o"
	@echo "... src/express/Express.i"
	@echo "... src/express/Express.s"
	@echo "... src/express/ExpressBase.o"
	@echo "... src/express/ExpressBase.i"
	@echo "... src/express/ExpressBase.s"
	@echo "... src/memory/MemInspect.o"
	@echo "... src/memory/MemInspect.i"
	@echo "... src/memory/MemInspect.s"
	@echo "... src/memory/MemoryPoolManager.o"
	@echo "... src/memory/MemoryPoolManager.i"
	@echo "... src/memory/MemoryPoolManager.s"
	@echo "... src/memory/SystemMemoryManager.o"
	@echo "... src/memory/SystemMemoryManager.i"
	@echo "... src/memory/SystemMemoryManager.s"
	@echo "... src/processor/AudioProcess.o"
	@echo "... src/processor/AudioProcess.i"
	@echo "... src/processor/AudioProcess.s"
	@echo "... src/processor/ClipPreProcess.o"
	@echo "... src/processor/ClipPreProcess.i"
	@echo "... src/processor/ClipPreProcess.s"
	@echo "... src/processor/FuyuPreProcess.o"
	@echo "... src/processor/FuyuPreProcess.i"
	@echo "... src/processor/FuyuPreProcess.s"
	@echo "... src/processor/PostProcess.o"
	@echo "... src/processor/PostProcess.i"
	@echo "... src/processor/PostProcess.s"
	@echo "... src/processor/PreProcess.o"
	@echo "... src/processor/PreProcess.i"
	@echo "... src/processor/PreProcess.s"
	@echo "... src/tokenizers/BPE/Bpe.o"
	@echo "... src/tokenizers/BPE/Bpe.i"
	@echo "... src/tokenizers/BPE/Bpe.s"
	@echo "... src/tokenizers/Tokenizer.o"
	@echo "... src/tokenizers/Tokenizer.i"
	@echo "... src/tokenizers/Tokenizer.s"
	@echo "... src/tokenizers/Unicode.o"
	@echo "... src/tokenizers/Unicode.i"
	@echo "... src/tokenizers/Unicode.s"
	@echo "... src/tokenizers/UnicodeData.o"
	@echo "... src/tokenizers/UnicodeData.i"
	@echo "... src/tokenizers/UnicodeData.s"
	@echo "... src/tokenizers/Unigram/Unigram.o"
	@echo "... src/tokenizers/Unigram/Unigram.i"
	@echo "... src/tokenizers/Unigram/Unigram.s"
	@echo "... src/tokenizers/WordPiece/WordPiece.o"
	@echo "... src/tokenizers/WordPiece/WordPiece.i"
	@echo "... src/tokenizers/WordPiece/WordPiece.s"
	@echo "... third_party/wenet_audio/feature_pipeline.o"
	@echo "... third_party/wenet_audio/feature_pipeline.i"
	@echo "... third_party/wenet_audio/feature_pipeline.s"
	@echo "... third_party/wenet_audio/fft.o"
	@echo "... third_party/wenet_audio/fft.i"
	@echo "... third_party/wenet_audio/fft.s"
	@echo "... tools/jni/LibHelper.o"
	@echo "... tools/jni/LibHelper.i"
	@echo "... tools/jni/LibHelper.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

